### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Rakshit",
    "email": "rakshit@example.com",
    "mobile": "9876543210",
    "mpin": "1234"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "upiId": "rakshit123@upi",
    "mpin": "1234"
}